Fully abstract records
edwinb/Idris2-boot pull request #292
Opened 2020-04-16 01:57 UTC by ohad

Add support for implicit and auto implicit parameters to records, with rig annotations.

This allows us to declare records such as:
```idris
data NotZero : Nat -> Type where
  Is : {n : Nat} -> NotZero (S n)

record Positive (n : Nat) {auto 0 pos : NotZero n} where
  constructor Check

a : Positive 1
a = Check

b : Positive 2
b = Check
```
(taken from the added `test/idris2/record003`)

I'm not sure anyone would want the irrelevance annotation in the type, but we might as well allow it.

This is my first independent tweak to (small parts of) the elaborator, so I'd be grateful for a thorough review.

The refactoring of the parser's `pibindList` through `pibindListName` might slow it down a little bit. I haven't profiled to see if it's substantial. If it is, we can inline `pibindListName` and add a `Just`.

2020-04-16 11:03 UTC, gallais requested changes
Not sure why so many `commit`s had to be removed in the parser. Is it because
of `{ ...` vs. `{ auto ...`? In this case the suggested refactoring should take
care of that.

2020-04-16 11:03 UTC, gallais commented on src/Idris/Parser.idr
> +  <|> do start <- location
You could write

```idris
 <|> do symbol "{"
         info <- (AutoImplicit <$ keyword "auto" <|> pure Implicit)
         commit
         start <- location
         params <- pibindListName fname start indents
         symbol "}"
         pure $ map (\(c, n, tm) => (n, c, info, tm)) params
```

2020-04-16 11:03 UTC, gallais commented on src/Idris/Syntax.idr
> +                                   <*> go4TupledPTerms ts
Isn't there a `PTerm` potentially hidden in the `PiInfo` too?

2020-04-16 12:04 UTC, ohad commented on src/Idris/Syntax.idr
> +                                   <*> go4TupledPTerms ts
Yes, well spotted, thanks. 
Will fix.

We should double-check with @edwinb about the status of default implicit arguments. I think at some point he wanted to move away from them in Idris2 and use `auto` implicits.

2020-04-17 07:39 UTC, ohad commented on src/Idris/Syntax.idr
> +                                   <*> go4TupledPTerms ts
Fixed. I'll poke @edwinb on slack

2020-04-17 08:26 UTC, ohad commented on src/Idris/Parser.idr
> +  <|> do start <- location
Done, thanks.
Idris needed a little bit of help with type annotations.

2020-04-17 08:53 UTC, ohad commented
OK, this is ready to be reviewed again.

2020-04-17 11:37 UTC, ohad commented
OK, I've added default arguments to record types, so this is ready to be merged.

(There's still a missing feature in allowing _fields_ to be auto / default implicits, but I'll leave that to the future.)

2020-04-17 14:04 UTC, gallais approved these changes

2020-04-19 10:31 UTC, ziman commented
I'm wondering about the auto implicit parameters (not fields).

Just to illustrate what I mean: in the case of `Positive`, I think I'd go for the following instead:
```idris
record Positive (n : Nat) where
  constructor Check
  {auto 0 isPositive : NotZero n}
```
Otherwise you wouldn't be able to even _talk about_ the positivity of numbers that have not already been proven to be positive.

I understand that `Positive` might be just a contrived example to avoid a lot of explanation. Besides, even my suggestion does not parse currently, so it's certainly good to add that.

But I still wonder if it's ever useful to have an auto implicit as a parameter of a _type_ constructor.

2020-04-19 10:34 UTC, ziman commented on src/Idris/Desugar.idr
> +           let _ = the (List (Name, RigCount, RawImp)) is'
Interesting, are these `let _ = the T x` forms type declarations? Are you adding them to aid humans or the type checker? Should `<-` have a way of declaring these types?

2020-04-19 14:00 UTC, ohad commented
> I understand that `Positive` might be just a contrived minimal example to avoid a lot of explanation. 

Yes, it's a contrived example :). 


> I'm wondering about the auto implicit parameters (not fields).
> 
> Just to illustrate what I mean: in the case of `Positive`, I think I'd go for the following instead:
> 
> ```idris
> record Positive (n : Nat) where
>   constructor Check
>   {auto 0 isPositive : NotZero n}
> ```

Yes, that's a much better way to do it. As I said above, we should add `auto` to fields at some point, though it's a bit less pressing to me than adding implicit arguments to the record type parameters. 

This is because, the `auto` implicit behaviour only affects the generated constructor, and so it is not a lot of hassle to add a 'smart constructor' instead.

2020-04-19 14:03 UTC, ohad commented on src/Idris/Desugar.idr
> +           let _ = the (List (Name, RigCount, RawImp)) is'
They're just a way to help the type-checker see what types are.

I think Idris2 is better about working this out anyway, and would probably have a more direct way to do it.

If `is'`was bound in a `let` instead of `<-`, then I could've moved the `the` statement into the bind. This way of doing it saves me mentioning the monad this is in. (In this case, `Core`, so not a big deal.)

2020-04-19 14:03 UTC, ohad commented
PS: thanks for taking a close look at this. I'm still a newb in this area, and the more eyeballs covering my patches, the better.

2020-04-21 09:59 UTC, edwinb commented
Thanks for the update and the useful discussion and reviewing! There may be more to tinker with, but this is a useful addition as it is now, I think.

2020-04-21 09:59 UTC, merged